# Generated by Django 4.1.2 on 2022-10-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booked_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('slot_date', models.DateField(blank=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionManager.session')),
            ],
        ),
    ]
