# Generated by Django 4.1.2 on 2022-10-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked_session',
            old_name='date_created',
            new_name='created_now',
        ),
    ]
