# Generated by Django 4.1.2 on 2022-10-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManager', '0003_remove_booked_session_created_now_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='members_count',
            field=models.IntegerField(default=12),
        ),
    ]
