# Generated by Django 4.1.2 on 2022-10-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SessionManager', '0004_session_members_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_session',
            name='user',
        ),
    ]
