# Generated by Django 4.1.2 on 2022-10-21 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SessionManager', '0006_booked_session_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booked_Session',
            new_name='BookSession',
        ),
    ]
