# Generated by Django 4.1.2 on 2022-10-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SessionManager', '0007_rename_booked_session_booksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ME',
            field=models.CharField(blank=True, choices=[('Morning', 'morning'), ('Evening', 'evening')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booksession',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
